#!/bin/sh
if [ -x /bin/systemctl ]; then
  systemctl daemon-reload >/dev/null 2>&1 || true
fi

case "$1" in
  upgrade)
    # systemd: start the new version
    if [ -x /bin/systemctl ]; then
      if [ systemctl status waarp-vitam-dip.service ]; then
        systemctl restart waarp-vitam-dip.service
      fi
      if [ systemctl status waarp-vitam-ingest.service ]; then
        systemctl restart waarp-vitam-ingest.service
      fi
      if [ systemctl status waarp-vitam-r66.service ]; then
        systemctl restart waarp-vitam-r66.service
      fi
    fi
    ;;

  purge)
    rm -rf /waarp/log/${unix.name} /waarp/conf/${unix.name} /waarp/tmp/${unix.name} /waarp/data/${unix.name}
    ;;

  remove|failed-upgrade|abort-install|abort-upgrade|disappear)
    ;;

   *)
    echo "postrm called with unknown argument \`$1'" >&2
    exit 1
    ;;
esac